### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by CarnufexG** [bpopp/Octoprint-Cura-Superslicer-Uploader#1]
I attempted to uninstall old version because new version will not install with previous version installed. Choosing uninstall from start menu opens control panel but there is no listing in the control panel for octoprintuploader.

**Comment by bpopp** [comment]
Yeah, I need to put together a better installer for it via Wix. I'm using the default Visual Studio Community deployment tools and they aren't very good. I'll take a look at this this week.

**Comment by bpopp** [comment]
This issue apparently comes up if you try to install a newer version from a different folder as a previous version. It's a goofy idiosyncrasy with the ClickOnce deployment I'm using. I need to switch to a better installer, but in the mean time, on most versions of Windows, you can reset your cache by deleting this folder:

C:\Users\\((your username))\AppData\Local\Apps

This should allow you to reinstall from any location. You'll see some other stuff in that folder, but it should rebuild the next time it's launched. I'll leave this open as a reminder to update the installer.

**Comment by CarnufexG** [comment]
Thanks... will give it a try today

**Comment by bpopp** [comment]
1.3 adds an installer which should hopefully assist w/ install/uninstall.
