### ISSUE TITLE
Uploader not hold settings on reboot

### ISSUE THREAD

**Issue by solexious** [bpopp/Octoprint-Cura-Superslicer-Uploader#3]
I've found that when the ui loads on a windows reboot its in the default state and lacks address, api, correct folder location along with check box selections.

On windows 10 with all updates, OctoprintUploader v 1.21

**Comment by bpopp** [comment]
Sole, I need to research this more closely, but see his thread for a possible workaround: https://github.com/bpopp/OctoprintUploader/issues/2
