### ISSUE TITLE
Two octoprint

### ISSUE THREAD

**Issue by ZhenyaKa** [bpopp/Octoprint-Cura-Superslicer-Uploader#4]
I have two printer with two Octoprint servers.

How to use two octoprint servers?

I can't install the second instance of this uploader!

**Comment by bpopp** [comment]
As far as I know, there's not a way currently. It's a good idea. I only have one printer currently, but I it would be nice to be able to tie one location to one config and a second to another. I'll add it to the list.

**Comment by ZhenyaKa** [comment]
Any news?

It will be OK run two version (just remove check that it already installed)

**Comment by bpopp** [comment]
Only took 6 years, but this has been added. Hopefully you're still printing. :)
