### ISSUE TITLE
Dosn't upload files

### ISSUE THREAD

**Issue by Ursus63** [bpopp/Octoprint-Cura-Superslicer-Uploader#6]
Hello. Programm dosn't upload file. Connection is ok. Check button says successfully connected.

**Comment by bpopp** [comment]
Sounds like you resolved this issue by adding http:// before the IP. If not, let me know.

**Comment by Ursus63** [comment]
No. That was another problem. Without http there was connection error when i push check. But now it is successfully connected and there is no reaction for any files in selected folder. 
I used your prorgamm about half of a year ago and all was fine. But a couple of month ago i reinstalled windows and now i want to use it again and nothing.
